### ISSUE TITLE
Add option to repeat parameter sets in the bytestream 

### ISSUE THREAD

**Issue by gBillal** [membraneframework/membrane_h264_plugin#31]
Having a byte stream that doesn't repeat parameter sets often (or provided out of band) can cause some issues on other part of the pipeline. An example is when we want to mux the stream into MP4 starting from a random position on the stream.

A fix is to add a boolean `repeat_parameter_sets` option to the `Parser`. If this option is set to `true`, the parameter sets will be pre-pended to each IDR access unit.

*If you think this may be a useful feature to have, I can work on it*

**Comment by varsill** [comment]
Hello @gBillal !
Your proposal sounds really good. 
I had just one concern - since PPS and SPS might be:
1) in-band of the stream, 
2) passed through element's options
3) parsed from DCR sent with `stream_format` 
we would need to decide which parameters should be in fact repeated, in case when there are parameters originating in multiple places (e.g. passed through options and in-band of the stream) After a discussion with my colleague from Membrane we have agreed that probably the best thing that can be done would be to repeat the latest parameters, no matter what their origin is. WDYT about such a solution?
We definitely find that feature useful and would really appreciate your contribution ;) 

Best wishes,
Łukasz

**Comment by gBillal** [comment]
At first I just wanted to repeat the parameter sets provided to the parser via options. Now that I read your suggestion, I think it makes more sense.

To summarize the repeat process:

- We'll repeat the latest parameter sets got from the `bytestream`, if there's none:
- Repeat parameter sets from the DCR, if there's none
- Repeat the provided parameter sets from the parser options, otherwise
- Do nothing

Is this the right order ?

**Comment by varsill** [comment]
Initially we thought about the solution you have described, but we have found a problem with it, concerning the `bytestream` parameters repetition. 

Imagine there is a stream of the following structure: 
`[SPS 1][PPS 1][IDR][NON_IDR]...[SPS 2][PPS 2][IDR][NON_IDR]...`
A stream receiver joining after `[SPS 2][PPS 2]` might still need to refer to `[SPS 1][PPS 1]` pair of parameters (PPS and SPS are referred to by their IDs and there is nothing limiting the further frames to refer to `[SPS 1][PPS 2]`). 
That is why we would need to keep in memory the maps of the following form `%{sps_id => sps_byte_payload}` and
`%{pps_id => pps_byte_payload}`, update it once new PPS and SPS are received and sent the "payload with parameters to be repeated" (consisting of concatenation of `sps_byte_payload` and `pps_byte_payload`) before every IDR.

Furthermore, since both the DCR parameters and the options parameters are put "in-band" of the stream by the parser (via the `frame_prefix`), I believe there is no need to distinguish between these 3 situations  - all of them can be treated as "bytestream" parameters.
All that needs to be done is properly updating of the "payload with parameters to be repeated" once handling the SPS and PPS in `handle_process`.

Best wishes,
Łukasz
